baseURL = "https://portfolio.n00bmind.me"
languageCode = "en-us"
title = "n00bmind's Portfolio"
theme = "terminal"
enableRobotsTXT = true
canonifyURLs = true
publishdir = "n00bmind.github.io"

[params]
    fullWidthTheme = false
    showLastUpdated = false
    centerTheme = true

[markup.goldmark.renderer]
    unsafe= true

[social]
    github= "https://github.com/n00bmind"
    linkedin= "https://www.linkedin.com/in/oscar-penas/"

[menu]
    [[menu.main]]
        identifier = "about"
        Name = "About"
        url = "/about/"
        weight = 0

    [[menu.main]]
        identifier = "experience"
        Name = "Experience"
        url = "/experience/"
        weight = 0

    [[menu.main]]
        identifier = "projects"
        Name = "Projects"
        url = "/projects/"
        weight = 0
